
apiVersion: v1
kind: Service
metadata:
  name: sectionsegmentation
  labels:
    run: sectionsegmentation
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    run: sectionsegmentation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sectionsegmentation
spec:
  selector:
    matchLabels:
      run: sectionsegmentation
  replicas: 1
  template:
    metadata:
      labels:
        run: sectionsegmentation
    spec:
      hostIPC: true
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
      containers:
      - name: sectionsegmentation
        image: jelenabanjac/brainsegmentation
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 2 # requesting 2 GPUs
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        volumeMounts:
        - name: devfuse
          mountPath: /dev/fuse
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
